# -*- coding: utf-8 -*-
"""data_augmentation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s7tJ2oeO7j7zh2ZNvA57Q3C7QivibXh-
"""

from tensorflow.keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img

img = load_img('/content/drive/MyDrive/Deep Learning Udemy/4 Veri Artırma Augmentation/araba.jpg')
x = img_to_array(img)
x.shape

# resimin array olarak okunması
x = x.reshape((1,) + x.shape)

datagen = ImageDataGenerator(rotation_range=40,
                             width_shift_range=0.2,
                             height_shift_range=0.2,
                             shear_range=0.2,
                             zoom_range=0.2,
                             horizontal_flip=True,
                             vertical_flip=True,
                             fill_mode='nearest')

veriler = datagen.flow(x, batch_size=1,
             save_to_dir='/content/drive/MyDrive/Deep Learning Udemy/4 Veri Artırma Augmentation/Artirilmis_Veri',
             save_format='jpeg')

i=0
for veri in veriler:   # 20 tane ek veri oluştur
  i=i+1
  if i==20:
    break

